#!/bin/bash

# String-Encryption-Vault Quick Reference Guide

echo "╔════════════════════════════════════════════════════════════╗"
echo "║  String-Encryption-Vault - Quick Reference Guide          ║"
echo "║     JavaScript/Node.js Edition for Hacktoberfest          ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""

echo "PROJECT STRUCTURE"
echo "──────────────────────────────────────────────────────────────"
echo "src/                     - Source code implementations"
echo "   ├── caesarCipher.js      (Implemented & Tested)"
echo "   ├── rot13.js             (Implemented & Tested)"
echo "   ├── base64Encoder.js     (Implemented & Tested)"
echo "   ├── vigenereCipher.js    (Stub - Ready for contribution)"
echo "   ├── passwordHasher.js    (Stub - Ready for contribution)"
echo "   ├── textObfuscator.js    (Stub - Ready for contribution)"
echo "   ├── morseCode.js         (Stub - Ready for contribution)"
echo "   ├── brailleConverter.js  (Stub - Ready for contribution)"
echo "   ├── qrDecoder.js         (Stub - Ready for contribution)"
echo "   └── index.js             - Main export file"
echo ""
echo "tests/                   - Jest tests (80%+ coverage)"
echo "   ├── caesarCipher.test.js (25+ test cases)"
echo "   ├── rot13.test.js        (15+ test cases)"
echo "   └── base64Encoder.test.js (15+ test cases)"
echo ""
echo "docs/                    - Comprehensive documentation"
echo "   ├── CONTRIBUTING.md      - How to contribute (Hacktoberfest guide)"
echo "   ├── DEVELOPMENT.md       - Development setup & workflow"
echo "   └── cipher_guide.md      - Educational explanations"
echo ""
echo "cli/                     - Command-line interface"
echo "   └── main.js              - CLI commands for all tools"
echo ""
echo "examples/                - Working examples"
echo "   └── usage_examples.js    - Demo of all features"
echo ""

echo ""
echo "QUICK START"
echo "──────────────────────────────────────────────────────────────"
echo "1. Install dependencies:"
echo "   $ npm install"
echo ""
echo "2. Run tests:"
echo "   $ npm test"
echo ""
echo "3. Try the CLI:"
echo "   $ npm run cli -- caesar --mode encrypt --text HELLO --shift 3"
echo ""
echo "4. Run examples:"
echo "   $ npm run example"
echo ""

echo ""
echo "NPM SCRIPTS"
echo "──────────────────────────────────────────────────────────────"
echo "npm test              - Run all tests with coverage"
echo "npm run test:watch    - Watch mode (re-run on changes)"
echo "npm run test:coverage - Generate detailed coverage report"
echo "npm run lint          - Check code quality"
echo "npm run lint:fix      - Auto-fix linting issues"
echo "npm run format        - Format code with Prettier"
echo "npm run format:check  - Check if formatting is needed"
echo "npm run cli           - Run CLI tool"
echo "npm run example       - Run usage examples"
echo ""

echo ""
echo "HACKTOBERFEST CONTRIBUTION WORKFLOW"
echo "──────────────────────────────────────────────────────────────"
echo "1. Fork the repository on GitHub"
echo ""
echo "2. Clone your fork:"
echo "   $ git clone https://github.com/YOUR-USERNAME/String-Encryption-Vault.git"
echo ""
echo "3. Create feature branch:"
echo "   $ git checkout -b feature/cipher-name"
echo ""
echo "4. Install dependencies:"
echo "   $ npm install"
echo ""
echo "5. Implement your feature in src/"
echo "   - Follow the template in docs/DEVELOPMENT.md"
echo "   - Add comprehensive JSDoc comments"
echo "   - Include usage examples"
echo ""
echo "6. Write tests in tests/"
echo "   - Aim for 80%+ coverage"
echo "   - Test edge cases"
echo "   - Test error handling"
echo ""
echo "7. Check code quality:"
echo "   $ npm run lint:fix"
echo "   $ npm run format"
echo "   $ npm test"
echo ""
echo "8. Commit with clear message:"
echo "   $ git commit -m \"feat: implement [cipher name]\""
echo ""
echo "9. Push to your fork:"
echo "   $ git push origin feature/cipher-name"
echo ""
echo "10. Create Pull Request on GitHub"
echo "   - Include clear description"
echo "   - Reference any issues"
echo "   - Wait for review & approval"
echo ""

echo ""
echo "READY-TO-IMPLEMENT FEATURES"
echo "──────────────────────────────────────────────────────────────"
echo "Vigenère Cipher           - Difficulty: Medium"
echo "   File: src/vigenereCipher.js"
echo "   Test: tests/vigenereCipher.test.js"
echo ""
echo "Password Hasher           - Difficulty: Easy"
echo "   File: src/passwordHasher.js"
echo "   Dependencies: bcrypt (already in package.json)"
echo ""
echo "Text Obfuscator           - Difficulty: Easy"
echo "   File: src/textObfuscator.js"
echo ""
echo "Morse Code               - Difficulty: Easy"
echo "   File: src/morseCode.js"
echo ""
echo "Braille Converter         - Difficulty: Medium"
echo "   File: src/brailleConverter.js"
echo "   Unicode Braille (U+2800-U+28FF)"
echo ""
echo "QR Code Decoder           - Difficulty: Medium"
echo "   File: src/qrDecoder.js"
echo "   Dependencies: qrcode (already in package.json)"
echo ""

echo ""
echo "USEFUL RESOURCES"
echo "──────────────────────────────────────────────────────────────"
echo "docs/CONTRIBUTING.md    - Detailed contribution guide"
echo "docs/DEVELOPMENT.md     - Development setup & templates"
echo "docs/cipher_guide.md    - How each cipher works"
echo "examples/usage_examples.js - Code examples"
echo "src/caesarCipher.js     - Well-commented reference"
echo "tests/caesarCipher.test.js - Test examples"
echo ""

echo ""
echo "WHAT'S INCLUDED"
echo "──────────────────────────────────────────────────────────────"
echo "3 fully implemented ciphers/encoders"
echo "50+ test cases with 80%+ coverage"
echo "ESLint configuration (airbnb-base rules)"
echo "Prettier code formatting"
echo "Jest testing framework"
echo "CLI tool with Commander"
echo "Comprehensive documentation"
echo "Working examples"
echo "Stub files for remaining features"
echo "MIT License"
echo ""

echo ""
echo "PROJECT HIGHLIGHTS"
echo "──────────────────────────────────────────────────────────────"
echo "Educational + Practical"
echo "Learn cryptography fundamentals"
echo "Real-world encryption examples"
echo "Well-tested code (Jest)"
echo "Comprehensive documentation"
echo "Easy for beginners"
echo "Perfect for Hacktoberfest"
echo "JavaScript/Node.js (Modern ES6+ modules)"
echo ""

echo ""
echo "╔════════════════════════════════════════════════════════════╗"
echo "║  Ready to contribute? Pick a feature and get started!      ║"
echo "║  See docs/CONTRIBUTING.md for detailed instructions       ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
